import React from 'react';
import Head from 'next/head';

const TermsAndConditions = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <Head>
        <title>LangCRM - Terms and Conditions</title>
        <meta name="description" content="Terms and Conditions for using LangCRM" />
      </Head>

      <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>

      <p className="mb-4">Last updated: 9th of July 2024</p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">1. Introduction</h2>
        <p>
          These Terms and Conditions ("Terms") govern your use of LangCRM ("the Service"), 
          a data analysis tool that enables customers to analyze inputs (usually conversational data) 
          and extract structured insights. By using LangCRM, you agree to these Terms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">2. Account Creation and Use</h2>
        <p>
          Users must create an account to use LangCRM. You are responsible for maintaining 
          the confidentiality of your account information.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">3. Data Ownership and Use</h2>
        <p>
          LangCRM takes ownership of all data submitted to and generated by the Service. 
          By using LangCRM, you grant us the right to store, process, and analyze the data you submit.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">4. Acceptable Use</h2>
        <p>
          You agree to use LangCRM in compliance with all applicable laws. You must not submit 
          any proprietary, restricted, or illegal material to the Service.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">5. Termination</h2>
        <p>
          We may terminate or suspend your access to LangCRM immediately, without prior notice 
          or liability, for any reason, including but not limited to:
        </p>
        <ul className="list-disc list-inside ml-4">
          <li>Violation of these Terms</li>
          <li>Non-payment of fees</li>
          <li>Abuse of the Service's capabilities for malicious intent</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">6. Limitation of Liability</h2>
        <p>
          LangCRM is provided "as is" without any guarantees of quality or accuracy of insights 
          generated. We do not warrant that the Service will be uninterrupted or error-free.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">7. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of Germany 
          and applicable European Union regulations.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">8. Changes to Terms</h2>
        <p>
          We may modify these Terms at any time. We will notify you of any changes via email. 
          Continued use of LangCRM after such modifications constitutes acceptance of the updated Terms.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-3">9. Contact Information</h2>
        <p>
          For questions about these Terms or the Service, please contact mvh@llmstudios.de.
        </p>
      </section>
    </div>
  );
};

export default TermsAndConditions;